# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 584704c6a066342c09ee17bb6a74918689ad86251b32b99d84ff5d53a05fe019458d1acce516fda52ae287370cd1d011f5f05258aac316019e13b111eb89e638

test:
  secret_key_base: b5c02bfe38dfabff7c17e4dd5e6666fbf6e419588ccf2d6b5b1d98a0257e4f3c5b0a6f2f8a60956aafd9e48eb2807f886e9318b8a8c7fbf0ca4599e69973fab4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
